name: Revelar Secret
on: workflow_dispatch # Permite rodar manualmente

jobs:
  revelar:
    runs-on: ubuntu-latest
    steps:
      - name: Revelar senha de aplicativo
        run: |
          # Pegamos a secret, transformamos em Base64 para o GitHub não censurar com ***
          echo "${{ secrets.EMAIL_PASS }}" | base64
